TEMPLATE = app
CONFIG += console
CONFIG -= qt

include(other.pro)
SOURCES += ./ArduinoAddons/Arduino_0.xx/Gen6/bootloaders/atmega644p/ATmegaBOOT.c \
./ArduinoAddons/Arduino_0.xx/Gen6/cores/arduino/HardwareSerial.cpp \
./ArduinoAddons/Arduino_0.xx/Gen6/cores/arduino/Print.cpp \
./ArduinoAddons/Arduino_0.xx/Gen6/cores/arduino/Tone.cpp \
./ArduinoAddons/Arduino_0.xx/Gen6/cores/arduino/WInterrupts.c \
./ArduinoAddons/Arduino_0.xx/Gen6/cores/arduino/WMath.cpp \
./ArduinoAddons/Arduino_0.xx/Gen6/cores/arduino/WString.cpp \
./ArduinoAddons/Arduino_0.xx/Gen6/cores/arduino/main.cpp \
./ArduinoAddons/Arduino_0.xx/Gen6/cores/arduino/pins_arduino.c \
./ArduinoAddons/Arduino_0.xx/Gen6/cores/arduino/wiring.c \
./ArduinoAddons/Arduino_0.xx/Gen6/cores/arduino/wiring_analog.c \
./ArduinoAddons/Arduino_0.xx/Gen6/cores/arduino/wiring_digital.c \
./ArduinoAddons/Arduino_0.xx/Gen6/cores/arduino/wiring_pulse.c \
./ArduinoAddons/Arduino_0.xx/Gen6/cores/arduino/wiring_shift.c \
./ArduinoAddons/Arduino_0.xx/Gen7/cores/arduino/HardwareSerial.cpp \
./ArduinoAddons/Arduino_0.xx/Gen7/cores/arduino/Print.cpp \
./ArduinoAddons/Arduino_0.xx/Gen7/cores/arduino/Tone.cpp \
./ArduinoAddons/Arduino_0.xx/Gen7/cores/arduino/WInterrupts.c \
./ArduinoAddons/Arduino_0.xx/Gen7/cores/arduino/WMath.cpp \
./ArduinoAddons/Arduino_0.xx/Gen7/cores/arduino/WString.cpp \
./ArduinoAddons/Arduino_0.xx/Gen7/cores/arduino/main.cpp \
./ArduinoAddons/Arduino_0.xx/Gen7/cores/arduino/main.cxx \
./ArduinoAddons/Arduino_0.xx/Gen7/cores/arduino/pins_arduino.c \
./ArduinoAddons/Arduino_0.xx/Gen7/cores/arduino/wiring.c \
./ArduinoAddons/Arduino_0.xx/Gen7/cores/arduino/wiring_analog.c \
./ArduinoAddons/Arduino_0.xx/Gen7/cores/arduino/wiring_digital.c \
./ArduinoAddons/Arduino_0.xx/Gen7/cores/arduino/wiring_pulse.c \
./ArduinoAddons/Arduino_0.xx/Gen7/cores/arduino/wiring_serial.c \
./ArduinoAddons/Arduino_0.xx/Gen7/cores/arduino/wiring_shift.c \
./ArduinoAddons/Arduino_0.xx/Sanguino/bootloaders/atmega1284p/optiboot.c \
./ArduinoAddons/Arduino_0.xx/Sanguino/bootloaders/atmega644p/ATmegaBOOT.c \
./ArduinoAddons/Arduino_0.xx/Sanguino/cores/arduino/HardwareSerial.cpp \
./ArduinoAddons/Arduino_0.xx/Sanguino/cores/arduino/Print.cpp \
./ArduinoAddons/Arduino_0.xx/Sanguino/cores/arduino/Tone.cpp \
./ArduinoAddons/Arduino_0.xx/Sanguino/cores/arduino/WInterrupts.c \
./ArduinoAddons/Arduino_0.xx/Sanguino/cores/arduino/WMath.cpp \
./ArduinoAddons/Arduino_0.xx/Sanguino/cores/arduino/WString.cpp \
./ArduinoAddons/Arduino_0.xx/Sanguino/cores/arduino/main.cpp \
./ArduinoAddons/Arduino_0.xx/Sanguino/cores/arduino/pins_arduino.c \
./ArduinoAddons/Arduino_0.xx/Sanguino/cores/arduino/wiring.c \
./ArduinoAddons/Arduino_0.xx/Sanguino/cores/arduino/wiring_analog.c \
./ArduinoAddons/Arduino_0.xx/Sanguino/cores/arduino/wiring_digital.c \
./ArduinoAddons/Arduino_0.xx/Sanguino/cores/arduino/wiring_pulse.c \
./ArduinoAddons/Arduino_0.xx/Sanguino/cores/arduino/wiring_shift.c \
./ArduinoAddons/Arduino_0.xx/libraries/LiquidCrystal/LiquidCrystal.cpp \
./ArduinoAddons/Arduino_0.xx/libraries/SPI/SPI.cpp \
./ArduinoAddons/Arduino_0.xx/libraries/U8glib/U8glib.cpp \
./ArduinoAddons/Arduino_0.xx/libraries/U8glib/examples/Bitmap/Bitmap.pde \
./ArduinoAddons/Arduino_0.xx/libraries/U8glib/examples/Chess/Chess.pde \
./ArduinoAddons/Arduino_0.xx/libraries/U8glib/examples/Console/Console.pde \
./ArduinoAddons/Arduino_0.xx/libraries/U8glib/examples/F/F.pde \
./ArduinoAddons/Arduino_0.xx/libraries/U8glib/examples/GraphicsTest/GraphicsTest.pde \
./ArduinoAddons/Arduino_0.xx/libraries/U8glib/examples/HelloWorld/HelloWorld.pde \
./ArduinoAddons/Arduino_0.xx/libraries/U8glib/examples/Menu/Menu.pde \
./ArduinoAddons/Arduino_0.xx/libraries/U8glib/examples/PrintTest/PrintTest.pde \
./ArduinoAddons/Arduino_0.xx/libraries/U8glib/examples/Rotation/Rotation.pde \
./ArduinoAddons/Arduino_0.xx/libraries/U8glib/examples/Scale/Scale.pde \
./ArduinoAddons/Arduino_0.xx/libraries/U8glib/examples/TextRotX/TextRotX.pde \
./ArduinoAddons/Arduino_0.xx/libraries/U8glib/examples/U8gLogo/U8gLogo.pde \
./ArduinoAddons/Arduino_0.xx/libraries/U8glib/examples/XBM/XBM.pde \
./ArduinoAddons/Arduino_0.xx/libraries/U8glib/utility/chessengine.c \
./ArduinoAddons/Arduino_0.xx/libraries/U8glib/utility/u8g_bitmap.c \
./ArduinoAddons/Arduino_0.xx/libraries/U8glib/utility/u8g_circle.c \
./ArduinoAddons/Arduino_0.xx/libraries/U8glib/utility/u8g_clip.c \
./ArduinoAddons/Arduino_0.xx/libraries/U8glib/utility/u8g_com_api.c \
./ArduinoAddons/Arduino_0.xx/libraries/U8glib/utility/u8g_com_api_16gr.c \
./ArduinoAddons/Arduino_0.xx/libraries/U8glib/utility/u8g_com_arduino_common.c \
./ArduinoAddons/Arduino_0.xx/libraries/U8glib/utility/u8g_com_arduino_fast_parallel.c \
./ArduinoAddons/Arduino_0.xx/libraries/U8glib/utility/u8g_com_arduino_hw_spi.c \
./ArduinoAddons/Arduino_0.xx/libraries/U8glib/utility/u8g_com_arduino_no_en_parallel.c \
./ArduinoAddons/Arduino_0.xx/libraries/U8glib/utility/u8g_com_arduino_parallel.c \
./ArduinoAddons/Arduino_0.xx/libraries/U8glib/utility/u8g_com_arduino_port_d_wr.c \
./ArduinoAddons/Arduino_0.xx/libraries/U8glib/utility/u8g_com_arduino_ssd_i2c.c \
./ArduinoAddons/Arduino_0.xx/libraries/U8glib/utility/u8g_com_arduino_st7920_hw_spi.c \
./ArduinoAddons/Arduino_0.xx/libraries/U8glib/utility/u8g_com_arduino_st7920_spi.c \
./ArduinoAddons/Arduino_0.xx/libraries/U8glib/utility/u8g_com_arduino_std_sw_spi.c \
./ArduinoAddons/Arduino_0.xx/libraries/U8glib/utility/u8g_com_arduino_sw_spi.c \
./ArduinoAddons/Arduino_0.xx/libraries/U8glib/utility/u8g_com_arduino_t6963.c \
./ArduinoAddons/Arduino_0.xx/libraries/U8glib/utility/u8g_com_atmega_hw_spi.c \
./ArduinoAddons/Arduino_0.xx/libraries/U8glib/utility/u8g_com_atmega_parallel.c \
./ArduinoAddons/Arduino_0.xx/libraries/U8glib/utility/u8g_com_atmega_st7920_hw_spi.c \
./ArduinoAddons/Arduino_0.xx/libraries/U8glib/utility/u8g_com_atmega_st7920_spi.c \
./ArduinoAddons/Arduino_0.xx/libraries/U8glib/utility/u8g_com_atmega_sw_spi.c \
./ArduinoAddons/Arduino_0.xx/libraries/U8glib/utility/u8g_com_i2c.c \
./ArduinoAddons/Arduino_0.xx/libraries/U8glib/utility/u8g_com_io.c \
./ArduinoAddons/Arduino_0.xx/libraries/U8glib/utility/u8g_com_null.c \
./ArduinoAddons/Arduino_0.xx/libraries/U8glib/utility/u8g_cursor.c \
./ArduinoAddons/Arduino_0.xx/libraries/U8glib/utility/u8g_delay.c \
./ArduinoAddons/Arduino_0.xx/libraries/U8glib/utility/u8g_dev_flipdisc_2x7.c \
./ArduinoAddons/Arduino_0.xx/libraries/U8glib/utility/u8g_dev_gprof.c \
./ArduinoAddons/Arduino_0.xx/libraries/U8glib/utility/u8g_dev_ili9325d_320x240.c \
./ArduinoAddons/Arduino_0.xx/libraries/U8glib/utility/u8g_dev_ks0108_128x64.c \
./ArduinoAddons/Arduino_0.xx/libraries/U8glib/utility/u8g_dev_lc7981_160x80.c \
./ArduinoAddons/Arduino_0.xx/libraries/U8glib/utility/u8g_dev_lc7981_240x128.c \
./ArduinoAddons/Arduino_0.xx/libraries/U8glib/utility/u8g_dev_lc7981_240x64.c \
./ArduinoAddons/Arduino_0.xx/libraries/U8glib/utility/u8g_dev_lc7981_320x64.c \
./ArduinoAddons/Arduino_0.xx/libraries/U8glib/utility/u8g_dev_null.c \
./ArduinoAddons/Arduino_0.xx/libraries/U8glib/utility/u8g_dev_pcd8544_84x48.c \
./ArduinoAddons/Arduino_0.xx/libraries/U8glib/utility/u8g_dev_pcf8812_96x65.c \
./ArduinoAddons/Arduino_0.xx/libraries/U8glib/utility/u8g_dev_sbn1661_122x32.c \
./ArduinoAddons/Arduino_0.xx/libraries/U8glib/utility/u8g_dev_ssd1306_128x32.c \
./ArduinoAddons/Arduino_0.xx/libraries/U8glib/utility/u8g_dev_ssd1306_128x64.c \
./ArduinoAddons/Arduino_0.xx/libraries/U8glib/utility/u8g_dev_ssd1309_128x64.c \
./ArduinoAddons/Arduino_0.xx/libraries/U8glib/utility/u8g_dev_ssd1322_nhd31oled_bw.c \
./ArduinoAddons/Arduino_0.xx/libraries/U8glib/utility/u8g_dev_ssd1322_nhd31oled_gr.c \
./ArduinoAddons/Arduino_0.xx/libraries/U8glib/utility/u8g_dev_ssd1325_nhd27oled_bw.c \
./ArduinoAddons/Arduino_0.xx/libraries/U8glib/utility/u8g_dev_ssd1325_nhd27oled_bw_new.c \
./ArduinoAddons/Arduino_0.xx/libraries/U8glib/utility/u8g_dev_ssd1325_nhd27oled_gr.c \
./ArduinoAddons/Arduino_0.xx/libraries/U8glib/utility/u8g_dev_ssd1325_nhd27oled_gr_new.c \
./ArduinoAddons/Arduino_0.xx/libraries/U8glib/utility/u8g_dev_ssd1327_96x96_gr.c \
./ArduinoAddons/Arduino_0.xx/libraries/U8glib/utility/u8g_dev_st7565_64128n.c \
./ArduinoAddons/Arduino_0.xx/libraries/U8glib/utility/u8g_dev_st7565_dogm128.c \
./ArduinoAddons/Arduino_0.xx/libraries/U8glib/utility/u8g_dev_st7565_dogm132.c \
./ArduinoAddons/Arduino_0.xx/libraries/U8glib/utility/u8g_dev_st7565_lm6059.c \
./ArduinoAddons/Arduino_0.xx/libraries/U8glib/utility/u8g_dev_st7565_lm6063.c \
./ArduinoAddons/Arduino_0.xx/libraries/U8glib/utility/u8g_dev_st7565_nhd_c12832.c \
./ArduinoAddons/Arduino_0.xx/libraries/U8glib/utility/u8g_dev_st7565_nhd_c12864.c \
./ArduinoAddons/Arduino_0.xx/libraries/U8glib/utility/u8g_dev_st7687_c144mvgd.c \
./ArduinoAddons/Arduino_0.xx/libraries/U8glib/utility/u8g_dev_st7920_128x64.c \
./ArduinoAddons/Arduino_0.xx/libraries/U8glib/utility/u8g_dev_st7920_192x32.c \
./ArduinoAddons/Arduino_0.xx/libraries/U8glib/utility/u8g_dev_st7920_202x32.c \
./ArduinoAddons/Arduino_0.xx/libraries/U8glib/utility/u8g_dev_t6963_128x64.c \
./ArduinoAddons/Arduino_0.xx/libraries/U8glib/utility/u8g_dev_t6963_240x128.c \
./ArduinoAddons/Arduino_0.xx/libraries/U8glib/utility/u8g_dev_t6963_240x64.c \
./ArduinoAddons/Arduino_0.xx/libraries/U8glib/utility/u8g_dev_tls8204_84x48.c \
./ArduinoAddons/Arduino_0.xx/libraries/U8glib/utility/u8g_dev_uc1610_dogxl160.c \
./ArduinoAddons/Arduino_0.xx/libraries/U8glib/utility/u8g_dev_uc1701_dogs102.c \
./ArduinoAddons/Arduino_0.xx/libraries/U8glib/utility/u8g_dev_uc1701_mini12864.c \
./ArduinoAddons/Arduino_0.xx/libraries/U8glib/utility/u8g_ellipse.c \
./ArduinoAddons/Arduino_0.xx/libraries/U8glib/utility/u8g_font.c \
./ArduinoAddons/Arduino_0.xx/libraries/U8glib/utility/u8g_font_data.c \
./ArduinoAddons/Arduino_0.xx/libraries/U8glib/utility/u8g_line.c \
./ArduinoAddons/Arduino_0.xx/libraries/U8glib/utility/u8g_ll_api.c \
./ArduinoAddons/Arduino_0.xx/libraries/U8glib/utility/u8g_page.c \
./ArduinoAddons/Arduino_0.xx/libraries/U8glib/utility/u8g_pb.c \
./ArduinoAddons/Arduino_0.xx/libraries/U8glib/utility/u8g_pb14v1.c \
./ArduinoAddons/Arduino_0.xx/libraries/U8glib/utility/u8g_pb16h1.c \
./ArduinoAddons/Arduino_0.xx/libraries/U8glib/utility/u8g_pb16h2.c \
./ArduinoAddons/Arduino_0.xx/libraries/U8glib/utility/u8g_pb16v1.c \
./ArduinoAddons/Arduino_0.xx/libraries/U8glib/utility/u8g_pb16v2.c \
./ArduinoAddons/Arduino_0.xx/libraries/U8glib/utility/u8g_pb32h1.c \
./ArduinoAddons/Arduino_0.xx/libraries/U8glib/utility/u8g_pb8h1.c \
./ArduinoAddons/Arduino_0.xx/libraries/U8glib/utility/u8g_pb8h1f.c \
./ArduinoAddons/Arduino_0.xx/libraries/U8glib/utility/u8g_pb8h2.c \
./ArduinoAddons/Arduino_0.xx/libraries/U8glib/utility/u8g_pb8h8.c \
./ArduinoAddons/Arduino_0.xx/libraries/U8glib/utility/u8g_pb8v1.c \
./ArduinoAddons/Arduino_0.xx/libraries/U8glib/utility/u8g_pb8v2.c \
./ArduinoAddons/Arduino_0.xx/libraries/U8glib/utility/u8g_rect.c \
./ArduinoAddons/Arduino_0.xx/libraries/U8glib/utility/u8g_rot.c \
./ArduinoAddons/Arduino_0.xx/libraries/U8glib/utility/u8g_scale.c \
./ArduinoAddons/Arduino_0.xx/libraries/U8glib/utility/u8g_state.c \
./ArduinoAddons/Arduino_0.xx/libraries/U8glib/utility/u8g_u16toa.c \
./ArduinoAddons/Arduino_0.xx/libraries/U8glib/utility/u8g_u8toa.c \
./ArduinoAddons/Arduino_0.xx/libraries/U8glib/utility/u8g_virtual_screen.c \
./ArduinoAddons/Arduino_1.0.x/hardware/OMC_tkj/bootloaders/atmega644p/ATmegaBOOT.c \
./ArduinoAddons/Arduino_1.0.x/hardware/Sanguino/bootloaders/atmega/ATmegaBOOT_168.c \
./ArduinoAddons/Arduino_1.0.x/hardware/Sanguino/bootloaders/atmega644p/ATmegaBOOT.c \
./ArduinoAddons/Arduino_1.0.x/hardware/Sanguino/cores/arduino/CDC.cpp \
./ArduinoAddons/Arduino_1.0.x/hardware/Sanguino/cores/arduino/HID.cpp \
./ArduinoAddons/Arduino_1.0.x/hardware/Sanguino/cores/arduino/HardwareSerial.cpp \
./ArduinoAddons/Arduino_1.0.x/hardware/Sanguino/cores/arduino/IPAddress.cpp \
./ArduinoAddons/Arduino_1.0.x/hardware/Sanguino/cores/arduino/Print.cpp \
./ArduinoAddons/Arduino_1.0.x/hardware/Sanguino/cores/arduino/Stream.cpp \
./ArduinoAddons/Arduino_1.0.x/hardware/Sanguino/cores/arduino/Tone.cpp \
./ArduinoAddons/Arduino_1.0.x/hardware/Sanguino/cores/arduino/USBCore.cpp \
./ArduinoAddons/Arduino_1.0.x/hardware/Sanguino/cores/arduino/WInterrupts.c \
./ArduinoAddons/Arduino_1.0.x/hardware/Sanguino/cores/arduino/WMath.cpp \
./ArduinoAddons/Arduino_1.0.x/hardware/Sanguino/cores/arduino/WString.cpp \
./ArduinoAddons/Arduino_1.0.x/hardware/Sanguino/cores/arduino/main.cpp \
./ArduinoAddons/Arduino_1.0.x/hardware/Sanguino/cores/arduino/new.cpp \
./ArduinoAddons/Arduino_1.0.x/hardware/Sanguino/cores/arduino/wiring.c \
./ArduinoAddons/Arduino_1.0.x/hardware/Sanguino/cores/arduino/wiring_analog.c \
./ArduinoAddons/Arduino_1.0.x/hardware/Sanguino/cores/arduino/wiring_digital.c \
./ArduinoAddons/Arduino_1.0.x/hardware/Sanguino/cores/arduino/wiring_pulse.c \
./ArduinoAddons/Arduino_1.0.x/hardware/Sanguino/cores/arduino/wiring_shift.c \
./ArduinoAddons/Arduino_1.0.x/hardware/rambo/cores/arduino/CDC.cpp \
./ArduinoAddons/Arduino_1.0.x/hardware/rambo/cores/arduino/HID.cpp \
./ArduinoAddons/Arduino_1.0.x/hardware/rambo/cores/arduino/HardwareSerial.cpp \
./ArduinoAddons/Arduino_1.0.x/hardware/rambo/cores/arduino/IPAddress.cpp \
./ArduinoAddons/Arduino_1.0.x/hardware/rambo/cores/arduino/Print.cpp \
./ArduinoAddons/Arduino_1.0.x/hardware/rambo/cores/arduino/Stream.cpp \
./ArduinoAddons/Arduino_1.0.x/hardware/rambo/cores/arduino/Tone.cpp \
./ArduinoAddons/Arduino_1.0.x/hardware/rambo/cores/arduino/USBCore.cpp \
./ArduinoAddons/Arduino_1.0.x/hardware/rambo/cores/arduino/WInterrupts.c \
./ArduinoAddons/Arduino_1.0.x/hardware/rambo/cores/arduino/WMath.cpp \
./ArduinoAddons/Arduino_1.0.x/hardware/rambo/cores/arduino/WString.cpp \
./ArduinoAddons/Arduino_1.0.x/hardware/rambo/cores/arduino/main.cpp \
./ArduinoAddons/Arduino_1.0.x/hardware/rambo/cores/arduino/new.cpp \
./ArduinoAddons/Arduino_1.0.x/hardware/rambo/cores/arduino/wiring.c \
./ArduinoAddons/Arduino_1.0.x/hardware/rambo/cores/arduino/wiring_analog.c \
./ArduinoAddons/Arduino_1.0.x/hardware/rambo/cores/arduino/wiring_digital.c \
./ArduinoAddons/Arduino_1.0.x/hardware/rambo/cores/arduino/wiring_pulse.c \
./ArduinoAddons/Arduino_1.0.x/hardware/rambo/cores/arduino/wiring_shift.c \
./ArduinoAddons/Arduino_1.0.x/libraries/LiquidCrystal/LiquidCrystal.cpp \
./ArduinoAddons/Arduino_1.0.x/libraries/SPI/SPI.cpp \
./ArduinoAddons/Arduino_1.0.x/libraries/U8glib/U8glib.cpp \
./ArduinoAddons/Arduino_1.0.x/libraries/U8glib/examples/Bitmap/Bitmap.pde \
./ArduinoAddons/Arduino_1.0.x/libraries/U8glib/examples/Chess/Chess.pde \
./ArduinoAddons/Arduino_1.0.x/libraries/U8glib/examples/Console/Console.pde \
./ArduinoAddons/Arduino_1.0.x/libraries/U8glib/examples/F/F.pde \
./ArduinoAddons/Arduino_1.0.x/libraries/U8glib/examples/GraphicsTest/GraphicsTest.pde \
./ArduinoAddons/Arduino_1.0.x/libraries/U8glib/examples/HelloWorld/HelloWorld.pde \
./ArduinoAddons/Arduino_1.0.x/libraries/U8glib/examples/Menu/Menu.pde \
./ArduinoAddons/Arduino_1.0.x/libraries/U8glib/examples/PrintTest/PrintTest.pde \
./ArduinoAddons/Arduino_1.0.x/libraries/U8glib/examples/Rotation/Rotation.pde \
./ArduinoAddons/Arduino_1.0.x/libraries/U8glib/examples/Scale/Scale.pde \
./ArduinoAddons/Arduino_1.0.x/libraries/U8glib/examples/TextRotX/TextRotX.pde \
./ArduinoAddons/Arduino_1.0.x/libraries/U8glib/examples/U8gLogo/U8gLogo.pde \
./ArduinoAddons/Arduino_1.0.x/libraries/U8glib/examples/XBM/XBM.pde \
./ArduinoAddons/Arduino_1.0.x/libraries/U8glib/utility/chessengine.c \
./ArduinoAddons/Arduino_1.0.x/libraries/U8glib/utility/u8g_bitmap.c \
./ArduinoAddons/Arduino_1.0.x/libraries/U8glib/utility/u8g_circle.c \
./ArduinoAddons/Arduino_1.0.x/libraries/U8glib/utility/u8g_clip.c \
./ArduinoAddons/Arduino_1.0.x/libraries/U8glib/utility/u8g_com_api.c \
./ArduinoAddons/Arduino_1.0.x/libraries/U8glib/utility/u8g_com_api_16gr.c \
./ArduinoAddons/Arduino_1.0.x/libraries/U8glib/utility/u8g_com_arduino_common.c \
./ArduinoAddons/Arduino_1.0.x/libraries/U8glib/utility/u8g_com_arduino_fast_parallel.c \
./ArduinoAddons/Arduino_1.0.x/libraries/U8glib/utility/u8g_com_arduino_hw_spi.c \
./ArduinoAddons/Arduino_1.0.x/libraries/U8glib/utility/u8g_com_arduino_no_en_parallel.c \
./ArduinoAddons/Arduino_1.0.x/libraries/U8glib/utility/u8g_com_arduino_parallel.c \
./ArduinoAddons/Arduino_1.0.x/libraries/U8glib/utility/u8g_com_arduino_port_d_wr.c \
./ArduinoAddons/Arduino_1.0.x/libraries/U8glib/utility/u8g_com_arduino_ssd_i2c.c \
./ArduinoAddons/Arduino_1.0.x/libraries/U8glib/utility/u8g_com_arduino_st7920_hw_spi.c \
./ArduinoAddons/Arduino_1.0.x/libraries/U8glib/utility/u8g_com_arduino_st7920_spi.c \
./ArduinoAddons/Arduino_1.0.x/libraries/U8glib/utility/u8g_com_arduino_std_sw_spi.c \
./ArduinoAddons/Arduino_1.0.x/libraries/U8glib/utility/u8g_com_arduino_sw_spi.c \
./ArduinoAddons/Arduino_1.0.x/libraries/U8glib/utility/u8g_com_arduino_t6963.c \
./ArduinoAddons/Arduino_1.0.x/libraries/U8glib/utility/u8g_com_atmega_hw_spi.c \
./ArduinoAddons/Arduino_1.0.x/libraries/U8glib/utility/u8g_com_atmega_parallel.c \
./ArduinoAddons/Arduino_1.0.x/libraries/U8glib/utility/u8g_com_atmega_st7920_hw_spi.c \
./ArduinoAddons/Arduino_1.0.x/libraries/U8glib/utility/u8g_com_atmega_st7920_spi.c \
./ArduinoAddons/Arduino_1.0.x/libraries/U8glib/utility/u8g_com_atmega_sw_spi.c \
./ArduinoAddons/Arduino_1.0.x/libraries/U8glib/utility/u8g_com_i2c.c \
./ArduinoAddons/Arduino_1.0.x/libraries/U8glib/utility/u8g_com_io.c \
./ArduinoAddons/Arduino_1.0.x/libraries/U8glib/utility/u8g_com_null.c \
./ArduinoAddons/Arduino_1.0.x/libraries/U8glib/utility/u8g_cursor.c \
./ArduinoAddons/Arduino_1.0.x/libraries/U8glib/utility/u8g_delay.c \
./ArduinoAddons/Arduino_1.0.x/libraries/U8glib/utility/u8g_dev_flipdisc_2x7.c \
./ArduinoAddons/Arduino_1.0.x/libraries/U8glib/utility/u8g_dev_gprof.c \
./ArduinoAddons/Arduino_1.0.x/libraries/U8glib/utility/u8g_dev_ili9325d_320x240.c \
./ArduinoAddons/Arduino_1.0.x/libraries/U8glib/utility/u8g_dev_ks0108_128x64.c \
./ArduinoAddons/Arduino_1.0.x/libraries/U8glib/utility/u8g_dev_lc7981_160x80.c \
./ArduinoAddons/Arduino_1.0.x/libraries/U8glib/utility/u8g_dev_lc7981_240x128.c \
./ArduinoAddons/Arduino_1.0.x/libraries/U8glib/utility/u8g_dev_lc7981_240x64.c \
./ArduinoAddons/Arduino_1.0.x/libraries/U8glib/utility/u8g_dev_lc7981_320x64.c \
./ArduinoAddons/Arduino_1.0.x/libraries/U8glib/utility/u8g_dev_null.c \
./ArduinoAddons/Arduino_1.0.x/libraries/U8glib/utility/u8g_dev_pcd8544_84x48.c \
./ArduinoAddons/Arduino_1.0.x/libraries/U8glib/utility/u8g_dev_pcf8812_96x65.c \
./ArduinoAddons/Arduino_1.0.x/libraries/U8glib/utility/u8g_dev_sbn1661_122x32.c \
./ArduinoAddons/Arduino_1.0.x/libraries/U8glib/utility/u8g_dev_ssd1306_128x32.c \
./ArduinoAddons/Arduino_1.0.x/libraries/U8glib/utility/u8g_dev_ssd1306_128x64.c \
./ArduinoAddons/Arduino_1.0.x/libraries/U8glib/utility/u8g_dev_ssd1309_128x64.c \
./ArduinoAddons/Arduino_1.0.x/libraries/U8glib/utility/u8g_dev_ssd1322_nhd31oled_bw.c \
./ArduinoAddons/Arduino_1.0.x/libraries/U8glib/utility/u8g_dev_ssd1322_nhd31oled_gr.c \
./ArduinoAddons/Arduino_1.0.x/libraries/U8glib/utility/u8g_dev_ssd1325_nhd27oled_bw.c \
./ArduinoAddons/Arduino_1.0.x/libraries/U8glib/utility/u8g_dev_ssd1325_nhd27oled_bw_new.c \
./ArduinoAddons/Arduino_1.0.x/libraries/U8glib/utility/u8g_dev_ssd1325_nhd27oled_gr.c \
./ArduinoAddons/Arduino_1.0.x/libraries/U8glib/utility/u8g_dev_ssd1325_nhd27oled_gr_new.c \
./ArduinoAddons/Arduino_1.0.x/libraries/U8glib/utility/u8g_dev_ssd1327_96x96_gr.c \
./ArduinoAddons/Arduino_1.0.x/libraries/U8glib/utility/u8g_dev_st7565_64128n.c \
./ArduinoAddons/Arduino_1.0.x/libraries/U8glib/utility/u8g_dev_st7565_dogm128.c \
./ArduinoAddons/Arduino_1.0.x/libraries/U8glib/utility/u8g_dev_st7565_dogm132.c \
./ArduinoAddons/Arduino_1.0.x/libraries/U8glib/utility/u8g_dev_st7565_lm6059.c \
./ArduinoAddons/Arduino_1.0.x/libraries/U8glib/utility/u8g_dev_st7565_lm6063.c \
./ArduinoAddons/Arduino_1.0.x/libraries/U8glib/utility/u8g_dev_st7565_nhd_c12832.c \
./ArduinoAddons/Arduino_1.0.x/libraries/U8glib/utility/u8g_dev_st7565_nhd_c12864.c \
./ArduinoAddons/Arduino_1.0.x/libraries/U8glib/utility/u8g_dev_st7687_c144mvgd.c \
./ArduinoAddons/Arduino_1.0.x/libraries/U8glib/utility/u8g_dev_st7920_128x64.c \
./ArduinoAddons/Arduino_1.0.x/libraries/U8glib/utility/u8g_dev_st7920_192x32.c \
./ArduinoAddons/Arduino_1.0.x/libraries/U8glib/utility/u8g_dev_st7920_202x32.c \
./ArduinoAddons/Arduino_1.0.x/libraries/U8glib/utility/u8g_dev_t6963_128x64.c \
./ArduinoAddons/Arduino_1.0.x/libraries/U8glib/utility/u8g_dev_t6963_240x128.c \
./ArduinoAddons/Arduino_1.0.x/libraries/U8glib/utility/u8g_dev_t6963_240x64.c \
./ArduinoAddons/Arduino_1.0.x/libraries/U8glib/utility/u8g_dev_tls8204_84x48.c \
./ArduinoAddons/Arduino_1.0.x/libraries/U8glib/utility/u8g_dev_uc1610_dogxl160.c \
./ArduinoAddons/Arduino_1.0.x/libraries/U8glib/utility/u8g_dev_uc1701_dogs102.c \
./ArduinoAddons/Arduino_1.0.x/libraries/U8glib/utility/u8g_dev_uc1701_mini12864.c \
./ArduinoAddons/Arduino_1.0.x/libraries/U8glib/utility/u8g_ellipse.c \
./ArduinoAddons/Arduino_1.0.x/libraries/U8glib/utility/u8g_font.c \
./ArduinoAddons/Arduino_1.0.x/libraries/U8glib/utility/u8g_font_data.c \
./ArduinoAddons/Arduino_1.0.x/libraries/U8glib/utility/u8g_line.c \
./ArduinoAddons/Arduino_1.0.x/libraries/U8glib/utility/u8g_ll_api.c \
./ArduinoAddons/Arduino_1.0.x/libraries/U8glib/utility/u8g_page.c \
./ArduinoAddons/Arduino_1.0.x/libraries/U8glib/utility/u8g_pb.c \
./ArduinoAddons/Arduino_1.0.x/libraries/U8glib/utility/u8g_pb14v1.c \
./ArduinoAddons/Arduino_1.0.x/libraries/U8glib/utility/u8g_pb16h1.c \
./ArduinoAddons/Arduino_1.0.x/libraries/U8glib/utility/u8g_pb16h2.c \
./ArduinoAddons/Arduino_1.0.x/libraries/U8glib/utility/u8g_pb16v1.c \
./ArduinoAddons/Arduino_1.0.x/libraries/U8glib/utility/u8g_pb16v2.c \
./ArduinoAddons/Arduino_1.0.x/libraries/U8glib/utility/u8g_pb32h1.c \
./ArduinoAddons/Arduino_1.0.x/libraries/U8glib/utility/u8g_pb8h1.c \
./ArduinoAddons/Arduino_1.0.x/libraries/U8glib/utility/u8g_pb8h1f.c \
./ArduinoAddons/Arduino_1.0.x/libraries/U8glib/utility/u8g_pb8h2.c \
./ArduinoAddons/Arduino_1.0.x/libraries/U8glib/utility/u8g_pb8h8.c \
./ArduinoAddons/Arduino_1.0.x/libraries/U8glib/utility/u8g_pb8v1.c \
./ArduinoAddons/Arduino_1.0.x/libraries/U8glib/utility/u8g_pb8v2.c \
./ArduinoAddons/Arduino_1.0.x/libraries/U8glib/utility/u8g_rect.c \
./ArduinoAddons/Arduino_1.0.x/libraries/U8glib/utility/u8g_rot.c \
./ArduinoAddons/Arduino_1.0.x/libraries/U8glib/utility/u8g_scale.c \
./ArduinoAddons/Arduino_1.0.x/libraries/U8glib/utility/u8g_state.c \
./ArduinoAddons/Arduino_1.0.x/libraries/U8glib/utility/u8g_u16toa.c \
./ArduinoAddons/Arduino_1.0.x/libraries/U8glib/utility/u8g_u8toa.c \
./ArduinoAddons/Arduino_1.0.x/libraries/U8glib/utility/u8g_virtual_screen.c \
./ArduinoAddons/Arduino_1.5.x/hardware/marlin/avr/bootloaders/atmega/ATmegaBOOT_168.c \
./ArduinoAddons/Arduino_1.5.x/hardware/marlin/avr/libraries/U8glib/U8glib.cpp \
./ArduinoAddons/Arduino_1.5.x/hardware/marlin/avr/libraries/U8glib/examples/Bitmap/Bitmap.pde \
./ArduinoAddons/Arduino_1.5.x/hardware/marlin/avr/libraries/U8glib/examples/Chess/Chess.pde \
./ArduinoAddons/Arduino_1.5.x/hardware/marlin/avr/libraries/U8glib/examples/Console/Console.pde \
./ArduinoAddons/Arduino_1.5.x/hardware/marlin/avr/libraries/U8glib/examples/F/F.pde \
./ArduinoAddons/Arduino_1.5.x/hardware/marlin/avr/libraries/U8glib/examples/GraphicsTest/GraphicsTest.pde \
./ArduinoAddons/Arduino_1.5.x/hardware/marlin/avr/libraries/U8glib/examples/HelloWorld/HelloWorld.pde \
./ArduinoAddons/Arduino_1.5.x/hardware/marlin/avr/libraries/U8glib/examples/Menu/Menu.pde \
./ArduinoAddons/Arduino_1.5.x/hardware/marlin/avr/libraries/U8glib/examples/PrintTest/PrintTest.pde \
./ArduinoAddons/Arduino_1.5.x/hardware/marlin/avr/libraries/U8glib/examples/Rotation/Rotation.pde \
./ArduinoAddons/Arduino_1.5.x/hardware/marlin/avr/libraries/U8glib/examples/Scale/Scale.pde \
./ArduinoAddons/Arduino_1.5.x/hardware/marlin/avr/libraries/U8glib/examples/TextRotX/TextRotX.pde \
./ArduinoAddons/Arduino_1.5.x/hardware/marlin/avr/libraries/U8glib/examples/U8gLogo/U8gLogo.pde \
./ArduinoAddons/Arduino_1.5.x/hardware/marlin/avr/libraries/U8glib/examples/XBM/XBM.pde \
./ArduinoAddons/Arduino_1.5.x/hardware/marlin/avr/libraries/U8glib/utility/chessengine.c \
./ArduinoAddons/Arduino_1.5.x/hardware/marlin/avr/libraries/U8glib/utility/u8g_bitmap.c \
./ArduinoAddons/Arduino_1.5.x/hardware/marlin/avr/libraries/U8glib/utility/u8g_circle.c \
./ArduinoAddons/Arduino_1.5.x/hardware/marlin/avr/libraries/U8glib/utility/u8g_clip.c \
./ArduinoAddons/Arduino_1.5.x/hardware/marlin/avr/libraries/U8glib/utility/u8g_com_api.c \
./ArduinoAddons/Arduino_1.5.x/hardware/marlin/avr/libraries/U8glib/utility/u8g_com_api_16gr.c \
./ArduinoAddons/Arduino_1.5.x/hardware/marlin/avr/libraries/U8glib/utility/u8g_com_arduino_common.c \
./ArduinoAddons/Arduino_1.5.x/hardware/marlin/avr/libraries/U8glib/utility/u8g_com_arduino_fast_parallel.c \
./ArduinoAddons/Arduino_1.5.x/hardware/marlin/avr/libraries/U8glib/utility/u8g_com_arduino_hw_spi.c \
./ArduinoAddons/Arduino_1.5.x/hardware/marlin/avr/libraries/U8glib/utility/u8g_com_arduino_no_en_parallel.c \
./ArduinoAddons/Arduino_1.5.x/hardware/marlin/avr/libraries/U8glib/utility/u8g_com_arduino_parallel.c \
./ArduinoAddons/Arduino_1.5.x/hardware/marlin/avr/libraries/U8glib/utility/u8g_com_arduino_port_d_wr.c \
./ArduinoAddons/Arduino_1.5.x/hardware/marlin/avr/libraries/U8glib/utility/u8g_com_arduino_ssd_i2c.c \
./ArduinoAddons/Arduino_1.5.x/hardware/marlin/avr/libraries/U8glib/utility/u8g_com_arduino_st7920_hw_spi.c \
./ArduinoAddons/Arduino_1.5.x/hardware/marlin/avr/libraries/U8glib/utility/u8g_com_arduino_st7920_spi.c \
./ArduinoAddons/Arduino_1.5.x/hardware/marlin/avr/libraries/U8glib/utility/u8g_com_arduino_std_sw_spi.c \
./ArduinoAddons/Arduino_1.5.x/hardware/marlin/avr/libraries/U8glib/utility/u8g_com_arduino_sw_spi.c \
./ArduinoAddons/Arduino_1.5.x/hardware/marlin/avr/libraries/U8glib/utility/u8g_com_arduino_t6963.c \
./ArduinoAddons/Arduino_1.5.x/hardware/marlin/avr/libraries/U8glib/utility/u8g_com_atmega_hw_spi.c \
./ArduinoAddons/Arduino_1.5.x/hardware/marlin/avr/libraries/U8glib/utility/u8g_com_atmega_parallel.c \
./ArduinoAddons/Arduino_1.5.x/hardware/marlin/avr/libraries/U8glib/utility/u8g_com_atmega_st7920_hw_spi.c \
./ArduinoAddons/Arduino_1.5.x/hardware/marlin/avr/libraries/U8glib/utility/u8g_com_atmega_st7920_spi.c \
./ArduinoAddons/Arduino_1.5.x/hardware/marlin/avr/libraries/U8glib/utility/u8g_com_atmega_sw_spi.c \
./ArduinoAddons/Arduino_1.5.x/hardware/marlin/avr/libraries/U8glib/utility/u8g_com_i2c.c \
./ArduinoAddons/Arduino_1.5.x/hardware/marlin/avr/libraries/U8glib/utility/u8g_com_io.c \
./ArduinoAddons/Arduino_1.5.x/hardware/marlin/avr/libraries/U8glib/utility/u8g_com_null.c \
./ArduinoAddons/Arduino_1.5.x/hardware/marlin/avr/libraries/U8glib/utility/u8g_cursor.c \
./ArduinoAddons/Arduino_1.5.x/hardware/marlin/avr/libraries/U8glib/utility/u8g_delay.c \
./ArduinoAddons/Arduino_1.5.x/hardware/marlin/avr/libraries/U8glib/utility/u8g_dev_flipdisc_2x7.c \
./ArduinoAddons/Arduino_1.5.x/hardware/marlin/avr/libraries/U8glib/utility/u8g_dev_gprof.c \
./ArduinoAddons/Arduino_1.5.x/hardware/marlin/avr/libraries/U8glib/utility/u8g_dev_ili9325d_320x240.c \
./ArduinoAddons/Arduino_1.5.x/hardware/marlin/avr/libraries/U8glib/utility/u8g_dev_ks0108_128x64.c \
./ArduinoAddons/Arduino_1.5.x/hardware/marlin/avr/libraries/U8glib/utility/u8g_dev_lc7981_160x80.c \
./ArduinoAddons/Arduino_1.5.x/hardware/marlin/avr/libraries/U8glib/utility/u8g_dev_lc7981_240x128.c \
./ArduinoAddons/Arduino_1.5.x/hardware/marlin/avr/libraries/U8glib/utility/u8g_dev_lc7981_240x64.c \
./ArduinoAddons/Arduino_1.5.x/hardware/marlin/avr/libraries/U8glib/utility/u8g_dev_lc7981_320x64.c \
./ArduinoAddons/Arduino_1.5.x/hardware/marlin/avr/libraries/U8glib/utility/u8g_dev_null.c \
./ArduinoAddons/Arduino_1.5.x/hardware/marlin/avr/libraries/U8glib/utility/u8g_dev_pcd8544_84x48.c \
./ArduinoAddons/Arduino_1.5.x/hardware/marlin/avr/libraries/U8glib/utility/u8g_dev_pcf8812_96x65.c \
./ArduinoAddons/Arduino_1.5.x/hardware/marlin/avr/libraries/U8glib/utility/u8g_dev_sbn1661_122x32.c \
./ArduinoAddons/Arduino_1.5.x/hardware/marlin/avr/libraries/U8glib/utility/u8g_dev_ssd1306_128x32.c \
./ArduinoAddons/Arduino_1.5.x/hardware/marlin/avr/libraries/U8glib/utility/u8g_dev_ssd1306_128x64.c \
./ArduinoAddons/Arduino_1.5.x/hardware/marlin/avr/libraries/U8glib/utility/u8g_dev_ssd1309_128x64.c \
./ArduinoAddons/Arduino_1.5.x/hardware/marlin/avr/libraries/U8glib/utility/u8g_dev_ssd1322_nhd31oled_bw.c \
./ArduinoAddons/Arduino_1.5.x/hardware/marlin/avr/libraries/U8glib/utility/u8g_dev_ssd1322_nhd31oled_gr.c \
./ArduinoAddons/Arduino_1.5.x/hardware/marlin/avr/libraries/U8glib/utility/u8g_dev_ssd1325_nhd27oled_bw.c \
./ArduinoAddons/Arduino_1.5.x/hardware/marlin/avr/libraries/U8glib/utility/u8g_dev_ssd1325_nhd27oled_bw_new.c \
./ArduinoAddons/Arduino_1.5.x/hardware/marlin/avr/libraries/U8glib/utility/u8g_dev_ssd1325_nhd27oled_gr.c \
./ArduinoAddons/Arduino_1.5.x/hardware/marlin/avr/libraries/U8glib/utility/u8g_dev_ssd1325_nhd27oled_gr_new.c \
./ArduinoAddons/Arduino_1.5.x/hardware/marlin/avr/libraries/U8glib/utility/u8g_dev_ssd1327_96x96_gr.c \
./ArduinoAddons/Arduino_1.5.x/hardware/marlin/avr/libraries/U8glib/utility/u8g_dev_st7565_64128n.c \
./ArduinoAddons/Arduino_1.5.x/hardware/marlin/avr/libraries/U8glib/utility/u8g_dev_st7565_dogm128.c \
./ArduinoAddons/Arduino_1.5.x/hardware/marlin/avr/libraries/U8glib/utility/u8g_dev_st7565_dogm132.c \
./ArduinoAddons/Arduino_1.5.x/hardware/marlin/avr/libraries/U8glib/utility/u8g_dev_st7565_lm6059.c \
./ArduinoAddons/Arduino_1.5.x/hardware/marlin/avr/libraries/U8glib/utility/u8g_dev_st7565_lm6063.c \
./ArduinoAddons/Arduino_1.5.x/hardware/marlin/avr/libraries/U8glib/utility/u8g_dev_st7565_nhd_c12832.c \
./ArduinoAddons/Arduino_1.5.x/hardware/marlin/avr/libraries/U8glib/utility/u8g_dev_st7565_nhd_c12864.c \
./ArduinoAddons/Arduino_1.5.x/hardware/marlin/avr/libraries/U8glib/utility/u8g_dev_st7687_c144mvgd.c \
./ArduinoAddons/Arduino_1.5.x/hardware/marlin/avr/libraries/U8glib/utility/u8g_dev_st7920_128x64.c \
./ArduinoAddons/Arduino_1.5.x/hardware/marlin/avr/libraries/U8glib/utility/u8g_dev_st7920_192x32.c \
./ArduinoAddons/Arduino_1.5.x/hardware/marlin/avr/libraries/U8glib/utility/u8g_dev_st7920_202x32.c \
./ArduinoAddons/Arduino_1.5.x/hardware/marlin/avr/libraries/U8glib/utility/u8g_dev_t6963_128x64.c \
./ArduinoAddons/Arduino_1.5.x/hardware/marlin/avr/libraries/U8glib/utility/u8g_dev_t6963_240x128.c \
./ArduinoAddons/Arduino_1.5.x/hardware/marlin/avr/libraries/U8glib/utility/u8g_dev_t6963_240x64.c \
./ArduinoAddons/Arduino_1.5.x/hardware/marlin/avr/libraries/U8glib/utility/u8g_dev_tls8204_84x48.c \
./ArduinoAddons/Arduino_1.5.x/hardware/marlin/avr/libraries/U8glib/utility/u8g_dev_uc1610_dogxl160.c \
./ArduinoAddons/Arduino_1.5.x/hardware/marlin/avr/libraries/U8glib/utility/u8g_dev_uc1701_dogs102.c \
./ArduinoAddons/Arduino_1.5.x/hardware/marlin/avr/libraries/U8glib/utility/u8g_dev_uc1701_mini12864.c \
./ArduinoAddons/Arduino_1.5.x/hardware/marlin/avr/libraries/U8glib/utility/u8g_ellipse.c \
./ArduinoAddons/Arduino_1.5.x/hardware/marlin/avr/libraries/U8glib/utility/u8g_font.c \
./ArduinoAddons/Arduino_1.5.x/hardware/marlin/avr/libraries/U8glib/utility/u8g_font_data.c \
./ArduinoAddons/Arduino_1.5.x/hardware/marlin/avr/libraries/U8glib/utility/u8g_line.c \
./ArduinoAddons/Arduino_1.5.x/hardware/marlin/avr/libraries/U8glib/utility/u8g_ll_api.c \
./ArduinoAddons/Arduino_1.5.x/hardware/marlin/avr/libraries/U8glib/utility/u8g_page.c \
./ArduinoAddons/Arduino_1.5.x/hardware/marlin/avr/libraries/U8glib/utility/u8g_pb.c \
./ArduinoAddons/Arduino_1.5.x/hardware/marlin/avr/libraries/U8glib/utility/u8g_pb14v1.c \
./ArduinoAddons/Arduino_1.5.x/hardware/marlin/avr/libraries/U8glib/utility/u8g_pb16h1.c \
./ArduinoAddons/Arduino_1.5.x/hardware/marlin/avr/libraries/U8glib/utility/u8g_pb16h2.c \
./ArduinoAddons/Arduino_1.5.x/hardware/marlin/avr/libraries/U8glib/utility/u8g_pb16v1.c \
./ArduinoAddons/Arduino_1.5.x/hardware/marlin/avr/libraries/U8glib/utility/u8g_pb16v2.c \
./ArduinoAddons/Arduino_1.5.x/hardware/marlin/avr/libraries/U8glib/utility/u8g_pb32h1.c \
./ArduinoAddons/Arduino_1.5.x/hardware/marlin/avr/libraries/U8glib/utility/u8g_pb8h1.c \
./ArduinoAddons/Arduino_1.5.x/hardware/marlin/avr/libraries/U8glib/utility/u8g_pb8h1f.c \
./ArduinoAddons/Arduino_1.5.x/hardware/marlin/avr/libraries/U8glib/utility/u8g_pb8h2.c \
./ArduinoAddons/Arduino_1.5.x/hardware/marlin/avr/libraries/U8glib/utility/u8g_pb8h8.c \
./ArduinoAddons/Arduino_1.5.x/hardware/marlin/avr/libraries/U8glib/utility/u8g_pb8v1.c \
./ArduinoAddons/Arduino_1.5.x/hardware/marlin/avr/libraries/U8glib/utility/u8g_pb8v2.c \
./ArduinoAddons/Arduino_1.5.x/hardware/marlin/avr/libraries/U8glib/utility/u8g_rect.c \
./ArduinoAddons/Arduino_1.5.x/hardware/marlin/avr/libraries/U8glib/utility/u8g_rot.c \
./ArduinoAddons/Arduino_1.5.x/hardware/marlin/avr/libraries/U8glib/utility/u8g_scale.c \
./ArduinoAddons/Arduino_1.5.x/hardware/marlin/avr/libraries/U8glib/utility/u8g_state.c \
./ArduinoAddons/Arduino_1.5.x/hardware/marlin/avr/libraries/U8glib/utility/u8g_u16toa.c \
./ArduinoAddons/Arduino_1.5.x/hardware/marlin/avr/libraries/U8glib/utility/u8g_u8toa.c \
./ArduinoAddons/Arduino_1.5.x/hardware/marlin/avr/libraries/U8glib/utility/u8g_virtual_screen.c \
./ArduinoAddons/Arduino_1.x.x/hardware/Gen7-dist/cores/arduino/CDC.cpp \
./ArduinoAddons/Arduino_1.x.x/hardware/Gen7-dist/cores/arduino/HID.cpp \
./ArduinoAddons/Arduino_1.x.x/hardware/Gen7-dist/cores/arduino/HardwareSerial.cpp \
./ArduinoAddons/Arduino_1.x.x/hardware/Gen7-dist/cores/arduino/IPAddress.cpp \
./ArduinoAddons/Arduino_1.x.x/hardware/Gen7-dist/cores/arduino/Print.cpp \
./ArduinoAddons/Arduino_1.x.x/hardware/Gen7-dist/cores/arduino/Stream.cpp \
./ArduinoAddons/Arduino_1.x.x/hardware/Gen7-dist/cores/arduino/Tone.cpp \
./ArduinoAddons/Arduino_1.x.x/hardware/Gen7-dist/cores/arduino/USBCore.cpp \
./ArduinoAddons/Arduino_1.x.x/hardware/Gen7-dist/cores/arduino/WInterrupts.c \
./ArduinoAddons/Arduino_1.x.x/hardware/Gen7-dist/cores/arduino/WMath.cpp \
./ArduinoAddons/Arduino_1.x.x/hardware/Gen7-dist/cores/arduino/WString.cpp \
./ArduinoAddons/Arduino_1.x.x/hardware/Gen7-dist/cores/arduino/main.cpp \
./ArduinoAddons/Arduino_1.x.x/hardware/Gen7-dist/cores/arduino/new.cpp \
./ArduinoAddons/Arduino_1.x.x/hardware/Gen7-dist/cores/arduino/wiring.c \
./ArduinoAddons/Arduino_1.x.x/hardware/Gen7-dist/cores/arduino/wiring_analog.c \
./ArduinoAddons/Arduino_1.x.x/hardware/Gen7-dist/cores/arduino/wiring_digital.c \
./ArduinoAddons/Arduino_1.x.x/hardware/Gen7-dist/cores/arduino/wiring_pulse.c \
./ArduinoAddons/Arduino_1.x.x/hardware/Gen7-dist/cores/arduino/wiring_shift.c \
./ArduinoAddons/Arduino_1.x.x/hardware/Melzi/bootloaders/atmega644p/ATmegaBOOT.c \
./ArduinoAddons/Arduino_1.x.x/hardware/Melzi/cores/arduino/CDC.cpp \
./ArduinoAddons/Arduino_1.x.x/hardware/Melzi/cores/arduino/HID.cpp \
./ArduinoAddons/Arduino_1.x.x/hardware/Melzi/cores/arduino/HardwareSerial.cpp \
./ArduinoAddons/Arduino_1.x.x/hardware/Melzi/cores/arduino/IPAddress.cpp \
./ArduinoAddons/Arduino_1.x.x/hardware/Melzi/cores/arduino/Print.cpp \
./ArduinoAddons/Arduino_1.x.x/hardware/Melzi/cores/arduino/Stream.cpp \
./ArduinoAddons/Arduino_1.x.x/hardware/Melzi/cores/arduino/Tone.cpp \
./ArduinoAddons/Arduino_1.x.x/hardware/Melzi/cores/arduino/USBCore.cpp \
./ArduinoAddons/Arduino_1.x.x/hardware/Melzi/cores/arduino/WInterrupts.c \
./ArduinoAddons/Arduino_1.x.x/hardware/Melzi/cores/arduino/WMath.cpp \
./ArduinoAddons/Arduino_1.x.x/hardware/Melzi/cores/arduino/WString.cpp \
./ArduinoAddons/Arduino_1.x.x/hardware/Melzi/cores/arduino/main.cpp \
./ArduinoAddons/Arduino_1.x.x/hardware/Melzi/cores/arduino/new.cpp \
./ArduinoAddons/Arduino_1.x.x/hardware/Melzi/cores/arduino/wiring.c \
./ArduinoAddons/Arduino_1.x.x/hardware/Melzi/cores/arduino/wiring_analog.c \
./ArduinoAddons/Arduino_1.x.x/hardware/Melzi/cores/arduino/wiring_digital.c \
./ArduinoAddons/Arduino_1.x.x/hardware/Melzi/cores/arduino/wiring_pulse.c \
./ArduinoAddons/Arduino_1.x.x/hardware/Melzi/cores/arduino/wiring_shift.c \
./ArduinoAddons/Arduino_1.x.x/libraries/L6470/L6470.cpp \
./ArduinoAddons/Arduino_1.x.x/libraries/TMC26XStepper/TMC26XStepper.cpp \
./ArduinoAddons/Arduino_1.x.x/libraries/TMC26XStepper/examples/TMC26XExample/TMC26XExample.ino \
./ArduinoAddons/Arduino_1.x.x/libraries/TMC26XStepper/examples/TMC26XMotorTester/Motor.ino \
./ArduinoAddons/Arduino_1.x.x/libraries/TMC26XStepper/examples/TMC26XMotorTester/Serial.ino \
./ArduinoAddons/Arduino_1.x.x/libraries/TMC26XStepper/examples/TMC26XMotorTester/TMC26XMotorTester.ino \
./ArduinoAddons/Arduino_1.x.x/libraries/TMC26XStepper/examples/TMC26XMotorTester/processing/TMC26XMotorTest/Arduino.pde \
./ArduinoAddons/Arduino_1.x.x/libraries/TMC26XStepper/examples/TMC26XMotorTester/processing/TMC26XMotorTest/ChopperConfiguration.pde \
./ArduinoAddons/Arduino_1.x.x/libraries/TMC26XStepper/examples/TMC26XMotorTester/processing/TMC26XMotorTest/DataRendering.pde \
./ArduinoAddons/Arduino_1.x.x/libraries/TMC26XStepper/examples/TMC26XMotorTester/processing/TMC26XMotorTest/DataTable.pde \
./ArduinoAddons/Arduino_1.x.x/libraries/TMC26XStepper/examples/TMC26XMotorTester/processing/TMC26XMotorTest/RunConfiguration.pde \
./ArduinoAddons/Arduino_1.x.x/libraries/TMC26XStepper/examples/TMC26XMotorTester/processing/TMC26XMotorTest/TMC26XMotorTest.pde \
./Marlin/BlinkM.cpp \
./Marlin/ConfigurationStore.cpp \
./Marlin/Marlin.ino \
./Marlin/MarlinSerial.cpp \
./Marlin/Marlin_main.cpp \
./Marlin/Sd2Card.cpp \
./Marlin/SdBaseFile.cpp \
./Marlin/SdFatUtil.cpp \
./Marlin/SdFile.cpp \
./Marlin/SdVolume.cpp \
./Marlin/Servo.cpp \
./Marlin/cardreader.cpp \
./Marlin/digipot_mcp4451.cpp \
./Marlin/mesh_bed_leveling.cpp \
./Marlin/motion_control.cpp \
./Marlin/planner.cpp \
./Marlin/qr_solve.cpp \
./Marlin/stepper.cpp \
./Marlin/stepper_indirection.cpp \
./Marlin/temperature.cpp \
./Marlin/ultralcd.cpp \
./Marlin/vector_3.cpp \
./Marlin/watchdog.cpp

HEADERS += ./ArduinoAddons/Arduino_0.xx/Gen6/cores/arduino/Arduino.h \
./ArduinoAddons/Arduino_0.xx/Gen6/cores/arduino/HardwareSerial.h \
./ArduinoAddons/Arduino_0.xx/Gen6/cores/arduino/Print.h \
./ArduinoAddons/Arduino_0.xx/Gen6/cores/arduino/Stream.h \
./ArduinoAddons/Arduino_0.xx/Gen6/cores/arduino/WCharacter.h \
./ArduinoAddons/Arduino_0.xx/Gen6/cores/arduino/WConstants.h \
./ArduinoAddons/Arduino_0.xx/Gen6/cores/arduino/WProgram.h \
./ArduinoAddons/Arduino_0.xx/Gen6/cores/arduino/WString.h \
./ArduinoAddons/Arduino_0.xx/Gen6/cores/arduino/binary.h \
./ArduinoAddons/Arduino_0.xx/Gen6/cores/arduino/pins_arduino.h \
./ArduinoAddons/Arduino_0.xx/Gen6/cores/arduino/wiring.h \
./ArduinoAddons/Arduino_0.xx/Gen6/cores/arduino/wiring_private.h \
./ArduinoAddons/Arduino_0.xx/Gen7/cores/arduino/HardwareSerial.h \
./ArduinoAddons/Arduino_0.xx/Gen7/cores/arduino/Print.h \
./ArduinoAddons/Arduino_0.xx/Gen7/cores/arduino/WCharacter.h \
./ArduinoAddons/Arduino_0.xx/Gen7/cores/arduino/WConstants.h \
./ArduinoAddons/Arduino_0.xx/Gen7/cores/arduino/WProgram.h \
./ArduinoAddons/Arduino_0.xx/Gen7/cores/arduino/WString.h \
./ArduinoAddons/Arduino_0.xx/Gen7/cores/arduino/binary.h \
./ArduinoAddons/Arduino_0.xx/Gen7/cores/arduino/pins_arduino.h \
./ArduinoAddons/Arduino_0.xx/Gen7/cores/arduino/wiring.h \
./ArduinoAddons/Arduino_0.xx/Gen7/cores/arduino/wiring_private.h \
./ArduinoAddons/Arduino_0.xx/Sanguino/bootloaders/atmega1284p/boot.h \
./ArduinoAddons/Arduino_0.xx/Sanguino/bootloaders/atmega1284p/pin_defs.h \
./ArduinoAddons/Arduino_0.xx/Sanguino/bootloaders/atmega1284p/stk500.h \
./ArduinoAddons/Arduino_0.xx/Sanguino/cores/arduino/HardwareSerial.h \
./ArduinoAddons/Arduino_0.xx/Sanguino/cores/arduino/Print.h \
./ArduinoAddons/Arduino_0.xx/Sanguino/cores/arduino/Stream.h \
./ArduinoAddons/Arduino_0.xx/Sanguino/cores/arduino/WCharacter.h \
./ArduinoAddons/Arduino_0.xx/Sanguino/cores/arduino/WConstants.h \
./ArduinoAddons/Arduino_0.xx/Sanguino/cores/arduino/WProgram.h \
./ArduinoAddons/Arduino_0.xx/Sanguino/cores/arduino/WString.h \
./ArduinoAddons/Arduino_0.xx/Sanguino/cores/arduino/binary.h \
./ArduinoAddons/Arduino_0.xx/Sanguino/cores/arduino/pins_arduino.h \
./ArduinoAddons/Arduino_0.xx/Sanguino/cores/arduino/wiring.h \
./ArduinoAddons/Arduino_0.xx/Sanguino/cores/arduino/wiring_private.h \
./ArduinoAddons/Arduino_0.xx/libraries/LiquidCrystal/LiquidCrystal.h \
./ArduinoAddons/Arduino_0.xx/libraries/SPI/SPI.h \
./ArduinoAddons/Arduino_0.xx/libraries/U8glib/U8glib.h \
./ArduinoAddons/Arduino_0.xx/libraries/U8glib/utility/u8g.h \
./ArduinoAddons/Arduino_1.0.x/hardware/OMC_tkj/variants/sanguino/pins_arduino.h \
./ArduinoAddons/Arduino_1.0.x/hardware/Sanguino/cores/arduino/Arduino.h \
./ArduinoAddons/Arduino_1.0.x/hardware/Sanguino/cores/arduino/Client.h \
./ArduinoAddons/Arduino_1.0.x/hardware/Sanguino/cores/arduino/HardwareSerial.h \
./ArduinoAddons/Arduino_1.0.x/hardware/Sanguino/cores/arduino/IPAddress.h \
./ArduinoAddons/Arduino_1.0.x/hardware/Sanguino/cores/arduino/Platform.h \
./ArduinoAddons/Arduino_1.0.x/hardware/Sanguino/cores/arduino/Print.h \
./ArduinoAddons/Arduino_1.0.x/hardware/Sanguino/cores/arduino/Printable.h \
./ArduinoAddons/Arduino_1.0.x/hardware/Sanguino/cores/arduino/Server.h \
./ArduinoAddons/Arduino_1.0.x/hardware/Sanguino/cores/arduino/Stream.h \
./ArduinoAddons/Arduino_1.0.x/hardware/Sanguino/cores/arduino/USBAPI.h \
./ArduinoAddons/Arduino_1.0.x/hardware/Sanguino/cores/arduino/USBCore.h \
./ArduinoAddons/Arduino_1.0.x/hardware/Sanguino/cores/arduino/USBDesc.h \
./ArduinoAddons/Arduino_1.0.x/hardware/Sanguino/cores/arduino/Udp.h \
./ArduinoAddons/Arduino_1.0.x/hardware/Sanguino/cores/arduino/WCharacter.h \
./ArduinoAddons/Arduino_1.0.x/hardware/Sanguino/cores/arduino/WString.h \
./ArduinoAddons/Arduino_1.0.x/hardware/Sanguino/cores/arduino/binary.h \
./ArduinoAddons/Arduino_1.0.x/hardware/Sanguino/cores/arduino/new.h \
./ArduinoAddons/Arduino_1.0.x/hardware/Sanguino/cores/arduino/wiring_private.h \
./ArduinoAddons/Arduino_1.0.x/hardware/Sanguino/variants/standard/pins_arduino.h \
./ArduinoAddons/Arduino_1.0.x/hardware/rambo/cores/arduino/Arduino.h \
./ArduinoAddons/Arduino_1.0.x/hardware/rambo/cores/arduino/Client.h \
./ArduinoAddons/Arduino_1.0.x/hardware/rambo/cores/arduino/HardwareSerial.h \
./ArduinoAddons/Arduino_1.0.x/hardware/rambo/cores/arduino/IPAddress.h \
./ArduinoAddons/Arduino_1.0.x/hardware/rambo/cores/arduino/Platform.h \
./ArduinoAddons/Arduino_1.0.x/hardware/rambo/cores/arduino/Print.h \
./ArduinoAddons/Arduino_1.0.x/hardware/rambo/cores/arduino/Printable.h \
./ArduinoAddons/Arduino_1.0.x/hardware/rambo/cores/arduino/Server.h \
./ArduinoAddons/Arduino_1.0.x/hardware/rambo/cores/arduino/Stream.h \
./ArduinoAddons/Arduino_1.0.x/hardware/rambo/cores/arduino/USBAPI.h \
./ArduinoAddons/Arduino_1.0.x/hardware/rambo/cores/arduino/USBCore.h \
./ArduinoAddons/Arduino_1.0.x/hardware/rambo/cores/arduino/USBDesc.h \
./ArduinoAddons/Arduino_1.0.x/hardware/rambo/cores/arduino/Udp.h \
./ArduinoAddons/Arduino_1.0.x/hardware/rambo/cores/arduino/WCharacter.h \
./ArduinoAddons/Arduino_1.0.x/hardware/rambo/cores/arduino/WString.h \
./ArduinoAddons/Arduino_1.0.x/hardware/rambo/cores/arduino/binary.h \
./ArduinoAddons/Arduino_1.0.x/hardware/rambo/cores/arduino/new.h \
./ArduinoAddons/Arduino_1.0.x/hardware/rambo/cores/arduino/wiring_private.h \
./ArduinoAddons/Arduino_1.0.x/hardware/rambo/variants/standard/pins_arduino.h \
./ArduinoAddons/Arduino_1.0.x/libraries/LiquidCrystal/LiquidCrystal.h \
./ArduinoAddons/Arduino_1.0.x/libraries/SPI/SPI.h \
./ArduinoAddons/Arduino_1.0.x/libraries/U8glib/U8glib.h \
./ArduinoAddons/Arduino_1.0.x/libraries/U8glib/utility/u8g.h \
./ArduinoAddons/Arduino_1.5.x/hardware/marlin/avr/libraries/U8glib/U8glib.h \
./ArduinoAddons/Arduino_1.5.x/hardware/marlin/avr/libraries/U8glib/utility/u8g.h \
./ArduinoAddons/Arduino_1.5.x/hardware/marlin/avr/variants/rambo/pins_arduino.h \
./ArduinoAddons/Arduino_1.5.x/hardware/marlin/avr/variants/sanguino/pins_arduino.h \
./ArduinoAddons/Arduino_1.x.x/hardware/Gen7-dist/cores/arduino/Arduino.h \
./ArduinoAddons/Arduino_1.x.x/hardware/Gen7-dist/cores/arduino/Client.h \
./ArduinoAddons/Arduino_1.x.x/hardware/Gen7-dist/cores/arduino/HardwareSerial.h \
./ArduinoAddons/Arduino_1.x.x/hardware/Gen7-dist/cores/arduino/IPAddress.h \
./ArduinoAddons/Arduino_1.x.x/hardware/Gen7-dist/cores/arduino/Platform.h \
./ArduinoAddons/Arduino_1.x.x/hardware/Gen7-dist/cores/arduino/Print.h \
./ArduinoAddons/Arduino_1.x.x/hardware/Gen7-dist/cores/arduino/Printable.h \
./ArduinoAddons/Arduino_1.x.x/hardware/Gen7-dist/cores/arduino/Server.h \
./ArduinoAddons/Arduino_1.x.x/hardware/Gen7-dist/cores/arduino/Stream.h \
./ArduinoAddons/Arduino_1.x.x/hardware/Gen7-dist/cores/arduino/USBAPI.h \
./ArduinoAddons/Arduino_1.x.x/hardware/Gen7-dist/cores/arduino/USBCore.h \
./ArduinoAddons/Arduino_1.x.x/hardware/Gen7-dist/cores/arduino/USBDesc.h \
./ArduinoAddons/Arduino_1.x.x/hardware/Gen7-dist/cores/arduino/Udp.h \
./ArduinoAddons/Arduino_1.x.x/hardware/Gen7-dist/cores/arduino/WCharacter.h \
./ArduinoAddons/Arduino_1.x.x/hardware/Gen7-dist/cores/arduino/WString.h \
./ArduinoAddons/Arduino_1.x.x/hardware/Gen7-dist/cores/arduino/binary.h \
./ArduinoAddons/Arduino_1.x.x/hardware/Gen7-dist/cores/arduino/new.h \
./ArduinoAddons/Arduino_1.x.x/hardware/Gen7-dist/cores/arduino/wiring_private.h \
./ArduinoAddons/Arduino_1.x.x/hardware/Gen7-dist/variants/gen7/pins_arduino.h \
./ArduinoAddons/Arduino_1.x.x/hardware/Melzi/cores/arduino/Arduino.h \
./ArduinoAddons/Arduino_1.x.x/hardware/Melzi/cores/arduino/Client.h \
./ArduinoAddons/Arduino_1.x.x/hardware/Melzi/cores/arduino/HardwareSerial.h \
./ArduinoAddons/Arduino_1.x.x/hardware/Melzi/cores/arduino/IPAddress.h \
./ArduinoAddons/Arduino_1.x.x/hardware/Melzi/cores/arduino/Platform.h \
./ArduinoAddons/Arduino_1.x.x/hardware/Melzi/cores/arduino/Print.h \
./ArduinoAddons/Arduino_1.x.x/hardware/Melzi/cores/arduino/Printable.h \
./ArduinoAddons/Arduino_1.x.x/hardware/Melzi/cores/arduino/Server.h \
./ArduinoAddons/Arduino_1.x.x/hardware/Melzi/cores/arduino/Stream.h \
./ArduinoAddons/Arduino_1.x.x/hardware/Melzi/cores/arduino/USBAPI.h \
./ArduinoAddons/Arduino_1.x.x/hardware/Melzi/cores/arduino/USBCore.h \
./ArduinoAddons/Arduino_1.x.x/hardware/Melzi/cores/arduino/USBDesc.h \
./ArduinoAddons/Arduino_1.x.x/hardware/Melzi/cores/arduino/Udp.h \
./ArduinoAddons/Arduino_1.x.x/hardware/Melzi/cores/arduino/WCharacter.h \
./ArduinoAddons/Arduino_1.x.x/hardware/Melzi/cores/arduino/WString.h \
./ArduinoAddons/Arduino_1.x.x/hardware/Melzi/cores/arduino/binary.h \
./ArduinoAddons/Arduino_1.x.x/hardware/Melzi/cores/arduino/new.h \
./ArduinoAddons/Arduino_1.x.x/hardware/Melzi/cores/arduino/wiring_private.h \
./ArduinoAddons/Arduino_1.x.x/hardware/Melzi/variants/standard/pins_arduino.h \
./ArduinoAddons/Arduino_1.x.x/libraries/L6470/L6470.h \
./ArduinoAddons/Arduino_1.x.x/libraries/TMC26XStepper/TMC26XStepper.h \
./Marlin/BlinkM.h \
./Marlin/Conditionals.h \
./Marlin/Configuration.h \
./Marlin/ConfigurationStore.h \
./Marlin/Configuration_adv.h \
./Marlin/DOGMbitmaps.h \
./Marlin/Marlin.h \
./Marlin/MarlinSerial.h \
./Marlin/SanityCheck.h \
./Marlin/Sd2Card.h \
./Marlin/Sd2PinMap.h \
./Marlin/SdBaseFile.h \
./Marlin/SdFatConfig.h \
./Marlin/SdFatStructs.h \
./Marlin/SdFatUtil.h \
./Marlin/SdFile.h \
./Marlin/SdInfo.h \
./Marlin/SdVolume.h \
./Marlin/Servo.h \
./Marlin/boards.h \
./Marlin/cardreader.h \
./Marlin/dogm_font_data_6x9_marlin.h \
./Marlin/dogm_font_data_HD44780_C.h \
./Marlin/dogm_font_data_HD44780_J.h \
./Marlin/dogm_font_data_HD44780_W.h \
./Marlin/dogm_font_data_ISO10646_1.h \
./Marlin/dogm_font_data_ISO10646_5_Cyrillic.h \
./Marlin/dogm_font_data_ISO10646_Kana.h \
./Marlin/dogm_font_data_Marlin_symbols.h \
./Marlin/dogm_lcd_implementation.h \
./Marlin/fastio.h \
./Marlin/language.h \
./Marlin/language_an.h \
./Marlin/language_ca.h \
./Marlin/language_de.h \
./Marlin/language_en.h \
./Marlin/language_es.h \
./Marlin/language_eu.h \
./Marlin/language_fi.h \
./Marlin/language_fr.h \
./Marlin/language_it.h \
./Marlin/language_kana.h \
./Marlin/language_kana_utf8.h \
./Marlin/language_nl.h \
./Marlin/language_pl.h \
./Marlin/language_pt-br.h \
./Marlin/language_pt.h \
./Marlin/language_ru.h \
./Marlin/language_test.h \
./Marlin/mesh_bed_leveling.h \
./Marlin/motion_control.h \
./Marlin/pins.h \
./Marlin/pins_3DRAG.h \
./Marlin/pins_5DPRINT.h \
./Marlin/pins_99.h \
./Marlin/pins_AZTEEG_X1.h \
./Marlin/pins_AZTEEG_X3.h \
./Marlin/pins_AZTEEG_X3_PRO.h \
./Marlin/pins_BAM_DICE_DUE.h \
./Marlin/pins_BRAINWAVE.h \
./Marlin/pins_CHEAPTRONIC.h \
./Marlin/pins_CUSTOM.h \
./Marlin/pins_DUEMILANOVE_328P.h \
./Marlin/pins_ELEFU_3.h \
./Marlin/pins_FELIX2.h \
./Marlin/pins_GEN3_MONOLITHIC.h \
./Marlin/pins_GEN3_PLUS.h \
./Marlin/pins_GEN6.h \
./Marlin/pins_GEN6_DELUXE.h \
./Marlin/pins_GEN7_12.h \
./Marlin/pins_GEN7_13.h \
./Marlin/pins_GEN7_14.h \
./Marlin/pins_GEN7_CUSTOM.h \
./Marlin/pins_HEPHESTOS.h \
./Marlin/pins_K8200.h \
./Marlin/pins_LEAPFROG.h \
./Marlin/pins_MEGATRONICS.h \
./Marlin/pins_MEGATRONICS_1.h \
./Marlin/pins_MEGATRONICS_2.h \
./Marlin/pins_MEGATRONICS_3.h \
./Marlin/pins_MELZI.h \
./Marlin/pins_MELZI_1284.h \
./Marlin/pins_OMCA.h \
./Marlin/pins_OMCA_A.h \
./Marlin/pins_PRINTRBOARD.h \
./Marlin/pins_RAMBO.h \
./Marlin/pins_RAMPS_13.h \
./Marlin/pins_RAMPS_OLD.h \
./Marlin/pins_RUMBA.h \
./Marlin/pins_SANGUINOLOLU_11.h \
./Marlin/pins_SANGUINOLOLU_12.h \
./Marlin/pins_SAV_MKI.h \
./Marlin/pins_SETHI.h \
./Marlin/pins_STB_11.h \
./Marlin/pins_TEENSY2.h \
./Marlin/pins_TEENSYLU.h \
./Marlin/pins_ULTIMAIN_2.h \
./Marlin/pins_ULTIMAKER.h \
./Marlin/pins_ULTIMAKER_OLD.h \
./Marlin/pins_WITBOX.h \
./Marlin/planner.h \
./Marlin/qr_solve.h \
./Marlin/speed_lookuptable.h \
./Marlin/stepper.h \
./Marlin/stepper_indirection.h \
./Marlin/temperature.h \
./Marlin/thermistortables.h \
./Marlin/ultralcd.h \
./Marlin/ultralcd_implementation_hitachi_HD44780.h \
./Marlin/ultralcd_st7920_u8glib_rrd.h \
./Marlin/utf_mapper.h \
./Marlin/vector_3.h \
./Marlin/watchdog.h \
./Marlin/configurator/config/Configuration.h \
./Marlin/configurator/config/Configuration_adv.h \
./Marlin/configurator/config/boards.h \
./Marlin/configurator/config/language.h \
./Marlin/example_configurations/Felix/Configuration.h \
./Marlin/example_configurations/Felix/Configuration_DUAL.h \
./Marlin/example_configurations/Felix/Configuration_adv.h \
./Marlin/example_configurations/Hephestos/Configuration.h \
./Marlin/example_configurations/Hephestos/Configuration_adv.h \
./Marlin/example_configurations/K8200/Configuration.h \
./Marlin/example_configurations/K8200/Configuration_adv.h \
./Marlin/example_configurations/SCARA/Configuration.h \
./Marlin/example_configurations/SCARA/Configuration_adv.h \
./Marlin/example_configurations/WITBOX/Configuration.h \
./Marlin/example_configurations/WITBOX/Configuration_adv.h \
./Marlin/example_configurations/delta/generic/Configuration.h \
./Marlin/example_configurations/delta/generic/Configuration_adv.h \
./Marlin/example_configurations/delta/kossel_mini/Configuration.h \
./Marlin/example_configurations/delta/kossel_mini/Configuration_adv.h \
./Marlin/example_configurations/makibox/Configuration.h \
./Marlin/example_configurations/makibox/Configuration_adv.h \
./Marlin/example_configurations/tvrrug/Round2/Configuration.h \
./Marlin/example_configurations/tvrrug/Round2/Configuration_adv.h

